name: "Continuous Integration (CI)"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  code-integration:
    name: Code Integration
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: "1.18"
      - name: Verify modules
        run: go mod verify
      - name: Unit tests
        run: go test -race ./...
      - name: Linter Staticcheck
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2022.1.3"
          install-go: false
          cache-key: "1.18"
      - name: Code analysis with sonar
        uses: sonarsource/sonarcloud-github-action@v1.9
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  vulns-scanner:
    name: Vulnerability Scanner
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/google/osv-scanner:v1.3.3
      volumes:
        - ${{ github.workspace }}:/github/workspace
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: OSV scanner
        run: /osv-scanner --lockfile=/github/workspace/go.mod
